### ISSUE TITLE
context-value UA rules for OpenType are giving unexpected rendering / compat problems

### ISSUE THREAD

**Issue by emilio** [w3c/svgwg#421]
https://www.w3.org/TR/SVG2/single-page.html#styling-UAStyleSheet says that in opentype glyphs a UA rule like the one following should apply:

```css
:root {
  fill: context-fill;
  fill-opacity: context-fill-opacity;
  stroke: context-stroke;
  stroke-opacity: context-stroke-opacity;
  stroke-width: context-value;
  stroke-dasharray: context-value;
  stroke-dashoffset: context-value;
}
```

Note that it mentions that the `context-value` keyword isn't defined in this specification, but I didn't find a way to file issues against https://docs.microsoft.com/en-us/typography/opentype/spec/svg.

The TL;DR is that that rule is causing us compat pain on Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1453451.

The definition of `context-value` is hand-waved in the spec, so it's not clear if the computed value of `context-value` should be `context-value`, or the actual used value.

If the first, that causes issues with fonts than don't expect it to inherit through (given properties like `stroke-width` are inherited). If the second, I don't think we can implement it efficiently and thus we may need to drop it.
