### ISSUE TITLE
Add support for the `hidden`-attribute

### ISSUE THREAD

**Issue by MichielBijl** [w3c/svgwg#508]
In the past I've run into the lack of support for the [`hidden`-attribute](http://w3c.github.io/html/editing.html#the-hidden-attribute) in SVG a few times. Today I saw a tweet that mentions this too. Were there ever plans to include support? And if not, are there good reasons not to include it?

**Comment by yatil** [comment]
`<w3c hat off>`

It seems very confusing to not allow it, especially, as outlined in the tweets above, when SVG is used inline in HTML.

**Comment by MichielBijl** [comment]
Thank you for your comments Amelia. Like you said, if nothing else, this will prevent a lot of confusion.

**Comment by simevidas** [comment]
The HTML standard [suggests](https://html.spec.whatwg.org/multipage/rendering.html#hidden-elements) that `[hidden] { display: none }` should be included in the user agent style sheet, so why aren’t browsers doing this? If they did, we wouldn’t have this problem to begin with, if I understand correctly.

**Comment by AmeliaBR** [comment]
@simevidas 

Because that HTML user-agent stylesheet is restricted to HTML-namespaced elements using a [CSS namespace rule](https://drafts.csswg.org/css-namespaces-3/#declaration):

```css
@namespace url(http://www.w3.org/1999/xhtml);

[hidden], area, base, basefont, datalist, head, link, meta, noembed,
noframes, param, rp, script, source, style, template, track, title {
  display: none;
}
```

One outcome of this issue would be to add a matching rule for SVG-namespaced elements, along with the global attribute and IDL property.
