### ISSUE TITLE
UA stylesheet seems to require title as display:  none but browsers do display: inline

### ISSUE THREAD

**Issue by domenic** [w3c/svgwg#828]
https://svgwg.org/svg2-draft/styling.html#UAStyleSheet says

```css
defs,
clipPath, mask, marker,
desc, title, metadata,
pattern, linearGradient, radialGradient,
script, style,
symbol {
  display: none !important;
}
```

(in the SVG namespace). However, browsers do not appear to respect this: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8961

At least one web developer seems to expect inline, not none: https://github.com/jsdom/jsdom/issues/3064

It's possible I'm reading the spec wrong?
